# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'supergui7.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Widget(object):
    def setupUi(self, Widget):
        Widget.setObjectName("Widget")
        Widget.resize(1161, 600)
        self.bg = QtWidgets.QLabel(Widget)
        self.bg.setGeometry(QtCore.QRect(-420, -40, 1741, 651))
        palette = QtGui.QPalette()
        self.bg.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Avengers")
        font.setPointSize(24)
        self.bg.setFont(font)
        self.bg.setStyleSheet("colour: rgb(74, 74, 74)")
        self.bg.setText("")
        self.bg.setPixmap(QtGui.QPixmap("Black_Template.jpg"))
        self.bg.setScaledContents(True)
        self.bg.setObjectName("bg")
        self.coding = QtWidgets.QLabel(Widget)
        self.coding.setGeometry(QtCore.QRect(0, 0, 331, 231))
        self.coding.setText("")
        self.coding.setPixmap(QtGui.QPixmap("coding.gif"))
        self.coding.setScaledContents(True)
        self.coding.setObjectName("coding")
        self.fridayname = QtWidgets.QLabel(Widget)
        self.fridayname.setGeometry(QtCore.QRect(420, 10, 231, 91))
        self.fridayname.setText("")
        self.fridayname.setPixmap(QtGui.QPixmap("friday.png"))
        self.fridayname.setScaledContents(True)
        self.fridayname.setObjectName("fridayname")
        self.arc = QtWidgets.QLabel(Widget)
        self.arc.setGeometry(QtCore.QRect(380, 100, 331, 211))
        self.arc.setText("")
        self.arc.setPixmap(QtGui.QPixmap("arc.gif"))
        self.arc.setScaledContents(True)
        self.arc.setObjectName("arc")
        self.voice = QtWidgets.QLabel(Widget)
        self.voice.setGeometry(QtCore.QRect(820, 20, 291, 221))
        self.voice.setText("")
        self.voice.setPixmap(QtGui.QPixmap("Ntuks.gif"))
        self.voice.setScaledContents(True)
        self.voice.setObjectName("voice")
        self.pushButton_2 = QtWidgets.QPushButton(Widget)
        self.pushButton_2.setGeometry(QtCore.QRect(900, 440, 161, 91))
        font = QtGui.QFont()
        font.setFamily("PMingLiU-ExtB")
        font.setPointSize(24)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"border-style: solid;\n"
"border-width: 2px;\n"
"border-color: #9999aa;\n"
"border-radius: 10px;\n"
"color: white;\n"
"background-color: qlineargradient(spread:pad, x1:0,5, y1:0, x2:0,5, y2:1, stop:0 rgba(0, 0, 255, 255), stop:1 rgba(255,\n"
"255, 255, 255));\n"
"}\n"
"QPushButton:enabled {\n"
"background-color: qlineargradient(spread:pad, x1:0,5, y1:0, x2:0,5, y2:1, stop:0 rgba(0, 0, 255, 255), stop:1 rgba(255,\n"
"255, 255, 255));\n"
"color: white;\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: qlineargradient(spread:pad, x1:0,5, y1:0, x2:0,5, y2:1, stop:0 rgba(0, 255, 255, 255), stop:1 rgba(255,\n"
"255, 255, 255));\n"
"color: #fffffe;\n"
"}\n"
"QPushButton:hover:!pressed {\n"
"background-color: qlineargradient(spread:pad, x1:0,5, y1:0, x2:0,5, y2:1, stop:0 rgba(255, 0, 255, 255), stop:1 rgba(255,\n"
"255, 255, 255));\n"
"color: #0c2f70;\n"
"}\n"
"QPushButton:disabled {\n"
"background-color: #aaaaaa;\n"
"color: #ffffff;\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.listen = QtWidgets.QLabel(Widget)
        self.listen.setGeometry(QtCore.QRect(780, 30, 351, 231))
        self.listen.setText("")
        self.listen.setPixmap(QtGui.QPixmap("listening.gif"))
        self.listen.setScaledContents(True)
        self.listen.setObjectName("listen")
        self.loading = QtWidgets.QLabel(Widget)
        self.loading.setGeometry(QtCore.QRect(810, 20, 311, 221))
        self.loading.setText("")
        self.loading.setPixmap(QtGui.QPixmap("loading.gif"))
        self.loading.setScaledContents(True)
        self.loading.setObjectName("loading")
        self.pushButton_3 = QtWidgets.QPushButton(Widget)
        self.pushButton_3.setGeometry(QtCore.QRect(900, 320, 161, 91))
        font = QtGui.QFont()
        font.setFamily("PMingLiU-ExtB")
        font.setPointSize(24)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("QPushButton {\n"
"border-style: solid;\n"
"border-width: 2px;\n"
"border-color: #9999aa;\n"
"border-radius: 10px;\n"
"color: white;\n"
"background-color: qlineargradient(spread:pad, x1:0,5, y1:0, x2:0,5, y2:1, stop:0 rgba(0, 0, 255, 255), stop:1 rgba(255,\n"
"255, 255, 255));\n"
"}\n"
"QPushButton:enabled {\n"
"background-color: qlineargradient(spread:pad, x1:0,5, y1:0, x2:0,5, y2:1, stop:0 rgba(0, 0, 255, 255), stop:1 rgba(255,\n"
"255, 255, 255));\n"
"color: white;\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: qlineargradient(spread:pad, x1:0,5, y1:0, x2:0,5, y2:1, stop:0 rgba(0, 255, 255, 255), stop:1 rgba(255,\n"
"255, 255, 255));\n"
"color: #fffffe;\n"
"}\n"
"QPushButton:hover:!pressed {\n"
"background-color: qlineargradient(spread:pad, x1:0,5, y1:0, x2:0,5, y2:1, stop:0 rgba(255, 0, 255, 255), stop:1 rgba(255,\n"
"255, 255, 255));\n"
"color: #0c2f70;\n"
"}\n"
"QPushButton:disabled {\n"
"background-color: #aaaaaa;\n"
"color: #ffffff;\n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.TERMINALOUTPUT = QtWidgets.QPlainTextEdit(Widget)
        self.TERMINALOUTPUT.setGeometry(QtCore.QRect(30, 330, 821, 211))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.TERMINALOUTPUT.setPalette(palette)
        self.TERMINALOUTPUT.setAutoFillBackground(True)
        self.TERMINALOUTPUT.setStyleSheet("color:rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);")
        self.TERMINALOUTPUT.setObjectName("TERMINALOUTPUT")
        self.lineEdit = QtWidgets.QLineEdit(Widget)
        self.lineEdit.setGeometry(QtCore.QRect(30, 540, 821, 21))
        self.lineEdit.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);")
        self.lineEdit.setObjectName("lineEdit")
        self.bg.raise_()
        self.listen.raise_()
        self.coding.raise_()
        self.fridayname.raise_()
        self.arc.raise_()
        self.pushButton_2.raise_()
        self.loading.raise_()
        self.voice.raise_()
        self.pushButton_3.raise_()
        self.TERMINALOUTPUT.raise_()
        self.lineEdit.raise_()

        self.retranslateUi(Widget)
        QtCore.QMetaObject.connectSlotsByName(Widget)

    def retranslateUi(self, Widget):
        _translate = QtCore.QCoreApplication.translate
        Widget.setWindowTitle(_translate("Widget", "Widget"))
        self.pushButton_2.setText(_translate("Widget", "EXIT"))
        self.pushButton_3.setText(_translate("Widget", "START"))
        self.TERMINALOUTPUT.setPlainText(_translate("Widget", "TERMINAL OUTPUT:\n"
""))
        self.lineEdit.setText(_translate("Widget", "ENTER YOUR COMMAND"))
import helo_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Widget = QtWidgets.QWidget()
    ui = Ui_Widget()
    ui.setupUi(Widget)
    Widget.show()
    sys.exit(app.exec_())
